markdown: rdiscount
pygments: true
permalink: /:title
rdiscount:
  extensions: [smart]

name: Swift
url: http://jobs.theycallmeswift.com
description: Jobs for hackers and other superheros.
email: swift@theycallmeswift.com
twitter: SwiftAlphaOne
github: theycallmeswift
gravatar_url: http://www.gravatar.com/avatar/10831877bd394c902f1dda20524c86d6
